// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/liuzhaomax/maxblog-main/internal/api"
	"github.com/liuzhaomax/maxblog-main/internal/core"
	"github.com/liuzhaomax/maxblog-main/internal/middleware"
	"github.com/liuzhaomax/maxblog-main/internal/middleware/auth"
	"github.com/liuzhaomax/maxblog-main/internal/middleware/reverse_proxy"
	"github.com/liuzhaomax/maxblog-main/internal/middleware/tracing"
	"github.com/liuzhaomax/maxblog-main/internal/middleware/validator"
	"github.com/liuzhaomax/maxblog-main/src/api_article/business"
	"github.com/liuzhaomax/maxblog-main/src/api_article/handler"
	"github.com/liuzhaomax/maxblog-main/src/api_article/model"
)

// Injectors from wire.go:

func InitInjector() (*Injector, func(), error) {
	engine := core.InitGinEngine()
	logger := core.InitLogrus()
	coreLogger := &core.Logger{
		Logger: logger,
	}
	client, cleanup, err := core.InitRedis()
	if err != nil {
		return nil, nil, err
	}
	authAuth := &auth.Auth{
		Logger: coreLogger,
		Redis:  client,
	}
	validatorValidator := &validator.Validator{
		Logger: coreLogger,
		Redis:  client,
	}
	configuration := core.InitTracer()
	tracingTracing := &tracing.Tracing{
		Logger:       coreLogger,
		TracerConfig: configuration,
	}
	reverseProxy := &reverse_proxy.ReverseProxy{
		Logger:      coreLogger,
		RedisClient: client,
	}
	middlewareMiddleware := &middleware.Middleware{
		Auth:         authAuth,
		Validator:    validatorValidator,
		Tracing:      tracingTracing,
		ReverseProxy: reverseProxy,
	}
	db, cleanup2, err := core.InitDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	modelArticle := &model.ModelArticle{
		DB: db,
	}
	trans := &core.Trans{
		DB: db,
	}
	businessArticle := &business.BusinessArticle{
		Model: modelArticle,
		Tx:    trans,
		Redis: client,
	}
	response := &core.Response{
		Logger: coreLogger,
	}
	rocketMQ := &core.RocketMQ{}
	handlerArticle := &handler.HandlerArticle{
		Business: businessArticle,
		Logger:   coreLogger,
		Res:      response,
		RocketMQ: rocketMQ,
	}
	registry := core.InitPrometheusRegistry()
	apiHandler := &api.Handler{
		Middleware:         middlewareMiddleware,
		HandlerArticle:     handlerArticle,
		PrometheusRegistry: registry,
	}
	injector := &Injector{
		Engine:  engine,
		Handler: apiHandler,
		DB:      db,
		Redis:   client,
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
